spring:
  datasource:
    driverClassName: org.postgresql.Driver
    username: secretuser
    password: secretpass
    url: jdbc:postgresql://localhost:5433/postgres
  jpa:
    generateDdl: true
    hibernate:
      ddlAuto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      javax:
        persistence:
          validation:
            mode: none



hotel-management:
  unaccepted-item-names: Free,Offer,Book,Website